name: Package Rocketchat

concurrency: ci-build

on:
  push: 
    branches: [main]
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:

  build:
    name: Chocolatey Build
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    #- name: Get content for sanity purposes
    #  run: |
    #    cat tools/chocolateyinstall.ps1
    #    cat rocketchat.nuspec    

    - name: Choco Package 
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: pack 

    - name: Rename file
      run: mv rocketchat*.nupkg rocketchat.nupkg

    - name: Choco add API key
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: apikey -y -k ${{ secrets.CHOCO_TOKEN }} --source https://push.chocolatey.org/

    - name: Push to Chocolatey
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: push rocketchat.nupkg -s https://push.chocolatey.org/
