name: Package Rocketchat

on:
  #schedule:
  #  - cron:  '30 * * * *'
  workflow_dispatch:

jobs:

  build:
    name: Chocolatey Build
    #needs: ["create_latest"]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get content for sanity purposes
      run: |
        cat tools/chocolateyinstall.ps1
        cat rocketchat.nuspec    

    - name: Choco Package 
      uses: crazy-max/ghaction-chocolatey@v2.1.0
      with:
        args: pack 

    - name: Rename file
      run: mv rocketchat*.nupkg rocketchat.nupkg

    - name: Choco add API key
      uses: crazy-max/ghaction-chocolatey@v2.1.0
      with:
        args: apikey -y -k ${{ secrets.CHOCO_TOKEN }} --source https://push.chocolatey.org/

    - name: Push to Chocolatey
      uses: crazy-max/ghaction-chocolatey@v2.1.0
      with:
        args: push rocketchat.nupkg -s https://push.chocolatey.org/
