# This is a basic workflow to help you get started with Actions
name: build

# Controls when the workflow will run
on: [push,workflow_dispatch]
# Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the latest version
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        shell: bash
        run: | 
          VERSION=$(curl -H 'Accept'='application/vnd.github.v3+json' -L "https://api.github.com/repos/RocketChat/Rocket.Chat.Electron/releases/latest" | jq -r .tag_name)
          echo $VERSION >> $GITHUB_ENV
      
      # Get checksum of latest exe
      - name: Get checksum
        id: get_checksum
        shell: bash
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          wget https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/$VERSION/rocketchat-setup-$VERSION.exe
          echo ::set-output name=checksum::$(md5sum rocketchat-setup-$VERSION.exe) >> $GITHUB_ENV

      # Runs a single command using the runners shell
      - name: Print checksum
        shell: bash
        run: echo ${{ steps.get_checksum.outputs.checksum}}
      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  shell: pwsh
      #  run: |
          

